"use strict";

module.exports = {
  meta: {
    name: "eslint-plugin-wxml",
    version: "0.8.0"
  },
  rules: {
    "colon-style-event-binding": require("./rules/colon-style-event-binding"),
    "empty-tag-self-closing": require("./rules/empty-tag-self-closing"),
    "event-binding-style": require("./rules/event-binding-style"),
    "forbid-attributes": require("./rules/forbid-attributes"),
    "forbid-tags": require("./rules/forbid-tags"),
    "max-depth": require("./rules/max-depth"),
    "max-len": require("./rules/max-len"),
    "max-lines": require("./rules/max-lines"),
    "no-const-and-let-in-wxs": require("./rules/no-const-and-let-in-wxs"),
    "no-dot-this-in-wx-key": require("./rules/no-dot-this-in-wx-key"),
    "no-duplicate-attributes": require("./rules/no-duplicate-attributes"),
    "no-index-in-wx-key": require("./rules/no-index-in-wx-key"),
    "no-dynamic-wx-key": require("./rules/no-dynamic-wx-key"),
    "no-inconsistent-tagname": require("./rules/no-inconsistent-tagname"),
    "no-inline-wxs": require("./rules/no-inline-wxs"),
    "no-unexpected-string-bool": require("./rules/no-unexpected-string-bool"),
    "no-unnecessary-block": require("./rules/no-unnecessary-block"),
    "no-vue-directive": require("./rules/no-vue-directive"),
    "no-wx-for-with-wx-else": require("./rules/no-wx-for-with-wx-else"),
    "no-wx-for-with-wx-if": require("./rules/no-wx-for-with-wx-if"),
    "no-wx-if-string": require("./rules/no-wx-if-string"),
    "omit-bool-attributes": require("./rules/omit-bool-attributes"),
    quotes: require("./rules/quotes"),
    "report-interpolation-error": require("./rules/report-interpolation-error"),
    "report-wxs-syntax-error": require("./rules/report-wxs-syntax-error"),
    "report-wxml-syntax-error": require("./rules/report-wxml-syntax-error"),
    "required-attributes": require("./rules/required-attributes"),
    "required-root-tag": require("./rules/required-root-tag"),
    "required-tags": require("./rules/required-tags"),
    "wx-key": require("./rules/wx-key"),
    "wxs-module-prop": require("./rules/wxs-module-prop"),
    "wxs-must-be-top-level": require("./rules/wxs-must-be-top-level"),
  },
  configs: {},
  processors: {
    wxml: require("./processor"),
  },
};
